before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
stages:
  - build-android
build_project:
  stage: build-android
  variables:
    UNI_OUTPUT_DIR: "./build"
    UNI_OUTPUT_NAME: "seesaw"
    UNI_DEFINE_SYMBOLS : "" 
    UNI_BUNDLE_IDENTIFIER :"com.gameon.seesaw"
    UNI_BUNDLE_VERSION:"1.0.$$CI_BUILD_ID"
    UNI_BUILD_OPT_RELEASE:"1"
    ANDROID_KEYSTORE_PATH : ""
    ANDROID_KEYSTORE_PASS: ""
    ANDROID_KEY_ALIAS_NAME: ""
    ANDROID_KEY_ALIAS_PASS: ""
  script:
    - /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchMode -executeMethod ProjectBuilderMenu.PerformAndroidBuild  -logFile /dev/stdout 
    
  only:
    - master
  artifacts:
    paths:
    - $UNI_OUTPUT_DIR/$UNI_OUTPUT_NAME.apk
    expire_in: 1 week
  tags:
    - unity
  when: manual